name: Daily CheckIn

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  check-in:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Update checkin time
        run: |
          date > last_checkin.txt
          
          git config --global user.name "checkin-bot"
          git config --global user.email "bot@github.com"
          
          git add last_checkin.txt
          git commit -m "Daily checkin $(date)" || true
          git push
